---
#ansible_ssh_common_args: '-o ProxyJump=nuc1.servers.bornhack.org'
poudriere_package_set: 'freebsd_13_0_amd64-default'
nginx_v4_proxy_ip: "85.209.118.162"
nginx_v6_proxy_ip: "2a09:94c4:55d1:7682::162"
ntp_pool_server: "dk.pool.ntp.org"
jail_host: "nuc1.servers.bornhack.org"
postgres_host: "postgres1.servers.bornhack.org"
syslog_server_ip: "syslog1.servers.bornhack.org"
dns_resolver_ips:
  - "2a09:94c4:55d1:76a0::2"
  - "10.1.0.2"
  - "91.239.100.100"
  - "89.233.43.71"
postgresql_version: "14"
