---
uwsgi_processes: 10
django_allowed_hostnames: '["mediastaging.bornhack.org"]'
django_postgres_user: "django6_servers_bornhack_org"
django_postgres_dbname: "django6_servers_bornhack_org_db"
django_cors_allowed_origins:
  - "https://wwwstaging.bornhack.org"
  - "http://127.0.0.1:8000"
django_bma_initial_groups: '["creators", "moderators", "curators"]'
nginx_client_max_body_size: "10000m"
django_email_realworld: true
django_email_user: "bmastaging@bornhack.org"
django_email_port: "587"
django_email_host: "asmtp.bornhack.org"
django_email_from: "bmastaging@bornhack.org"
...
