---
nginx_proxy: True
nginx_v4_proxy_ip: "85.209.118.164"
nginx_v6_proxy_ip: "2a09:94c4:55d1:7682::164"

dkimdns:
  smtp2.servers.bornhack.org: "v=DKIM1; k=rsa; s=email; p=MIIBJjANBgkqhkiG9w0BAQEFAAOCARMAMIIBDgKCAQUKhX6Zr3jtdWVqk68asWjI9IscCOBBd3LtAr1fxE5MJwSSFjXoPTlDKXRAY/W/AiPXeNkrtcyN/SDgA/1B/UEapKyeoSrTQuk0HY+74+YZrMdMqVV1Ma+9fWvxrt9fF3EGoahB6c5WiNKIUc5cdzbFGbzdt2q0zXduR9AqngBc8m1hDKajJ6nUzBXOxRvkrVtZiy/KHtfjxHY/7FHgb9hrLfZoIrhIROiN8f35WgiRskCP9JoWwqOWegkxC0CYVm7+V+kL/W8WXyJ35UcQZDWNpps3P+rhRBpngVMMqicN2SsrlmyO2pBKRtbyBtRggdhBFmKalDXMRoGwcQCFCtUMz0M4VJ8CAwEAAQ=="
  bornhack.dk: "v=DKIM1; k=rsa; s=email; p=MIIBJjANBgkqhkiG9w0BAQEFAAOCARMAMIIBDgKCAQULNgFStxTHhlZxfI+JwpovDl0JQ2pi/YILkxyyPj0t3F8o0LS4IkzrPwukA7RBhjbU8A74JJ0jUrSVt1p0YkwTWHMv3FTh8VTIOAauDX11mTN5/rGyVpkRLBP2N3upgjVwguUjk9tfHDgIt4W5ysn5739Qa6YN700zcin1T1F6GVE1lg2FFZe6iKh0PSS13n/EGDk4d7zdslxWfGOKs8FlFsgnAyYhZN5njEj20eQ4yOU0p3HuakTj7HWG6tLbZJoGdce6QVCnRBVQ0AZrDnv+MPYOORjhtxbgcWZCX1Fss7I+ZSMEQElGchxCgIGIG+HWePngbW3oBmLQprLPXAAEcNSeOBsCAwEAAQ=="
  bornhack.org: "v=DKIM1; k=rsa; s=email; p=MIIBJjANBgkqhkiG9w0BAQEFAAOCARMAMIIBDgKCAQUMvHxEJM0zKnMw9YmVh+KqHQggL49eKfK4xgroBUJDZYyKEW9DGRcG8m/Or2RCcIdRb518TGOpgUHwtvdIlElORInTjNEAT0H3cE8mR0oMPNc9n2NfSnZNb99b0RAfe92Nlx5q+XkLESZz0n+wLzXWVgeX4g2gCffFuWKkrEutCRuaC2FWi+pgvTvtClE00FHYOi+TLA2y10FfrT5JoVboLBCIDxwkRu3OagfP4ht5YBo6E6crFsf+/iPNs1+jOx+VxUtCRIHAX9mViEkIDcX/2cI+v8omzyQBnJ1Gyl3whrMKp3cyEqfodyRr/xoY5pRJo5jFA7z048rKA/F9gYY4iyrn8EkCAwEAAQ=="
  bornhack.com: "v=DKIM1; k=rsa; s=email; p=MIIBJjANBgkqhkiG9w0BAQEFAAOCARMAMIIBDgKCAQUMX5vNyRVGLDmBNeb0KwTpYnwI8lGyliaP3rrKn95oveOl1h6oac3GuGgl0PwA10Vp0+nT1BDVHwSx1PZjIL/b5Wilw0m36IwLH+pZqVIiqYegaXfCASfxzG0EEbJwj3U490OZTxVdKSW4AtitOjL2I++KqsmG40FLRDeM48e4CJbw/jZIwuIPl41jyKnzB9WPPeuo4Xhhc2Ep6Rth0pwjb+SqGrGrIcooZPGjO5NUmZoL01Ee1pWJIWkCFrHJi4/uWCyTKG0INmsYMYPAJNbwAt3P16B+0CDD9M6k9XHzF6u3Mm3NERVQSaOiLh1chLQ5+714uN/iFhtUsYQ5r+L2zveQBB8CAwEAAQ=="
  bornhack.camp: "v=DKIM1; k=rsa; s=email; p=MIIBJjANBgkqhkiG9w0BAQEFAAOCARMAMIIBDgKCAQUN6KmEnx8/Wg39Gx5c4z+Kd7JN3oMPIbHvRfoBLSFDZe2XK5IVfPqxnK8j/JOmQTGhVnGNjirCtCJIttuAZHOqdVkWua/mdbMSVHQnBRqtk26/1W5eM4reD95CWXfJ704hrzBiXTafdcbNmydEK03E1Xu1huvddauifqCaiTarL5XBhwQk6vYycRYd9AqpQUl4vnEPipL3f6ewqkmKOkFNO/bAqrt3vIWobgZpJSi8/Xc5xb8/VspOF2zXqPJg9Q2qEDR3bo8KNZaVf5mQf3yrCmt+tXYKSaLlnvrWdD3mtGr+H1hseeERxfh2RNl3gnNGeRi1uvnIi7Xgkg83R4v0Uxit/YMCAwEAAQ=="
  bornhack.info: "v=DKIM1; k=rsa; s=email; p=MIIBJjANBgkqhkiG9w0BAQEFAAOCARMAMIIBDgKCAQUNf2/hxb3K4vZKAxO2ZjF6m07FR9lgkgtikZD1egmwyL45GoYcxSjAScn4pUto60WtzlKGRPD/wZgMrNgKye84VJSUbNKLVfoLx7zIWRvsmoN6txukED+PXARlWADce+G7WpgXCErTQm2iKJ13Qm72YMOIHsD2BbeLp0wyB8v9L9SYpEt+9hw9BzNJvQ3KAUKVYBaE5LZHwukbAaO2F07cUNm1nUoqb3BCEkT+IVe2FmJelqYP9M2RfGVEfyjU1jcziqMsUloQtvuZ+SdCnsS5gY7P3lJnSf2kPJyZ3JLl0KIclNCQcKgUnBJcx/DJhvyLLmawwME9HafNjsHvMG8qpN+TSY8CAwEAAQ=="
  bornhack.net: "v=DKIM1; k=rsa; s=email; p=MIIBJjANBgkqhkiG9w0BAQEFAAOCARMAMIIBDgKCAQUNg2fNsLujJeGYz/pxHv7nuXBfk2otC+DWeAWM1K3P2zO349AvZsOoLJUxy9LcSJxXoi17p5Ii3b3cBVDkSPreuJhsnFUF60rfOU6rK2LYKmoxp9NP9ZqQy9/HGEuBKxB3/Uo07FZLaOO9juPcCQGv5i0Qed9tj2hr/306frizFG981cAzSh7ZQ2q0JRF3CG63hG/yICarpAy3xeANXAkBlxsSoiDkc3l52WFhzgWmfjLySzoR+tGE4US7bwHCtX76Z1Sef7aiaR1PJTh7WsE4LrJ83U74grhVwEaOSyxjs4M1oz21u9byXEuNuIEhUi59vDKQ4yGkd9AF5HD3+iLe11U9EukCAwEAAQ=="
  bornhack.social: "v=DKIM1; k=rsa; s=email; p=MIIBJjANBgkqhkiG9w0BAQEFAAOCARMAMIIBDgKCAQUM7d7b3NOiRTVxmDxi/OgH5YzRp7gfw/EU58WVjt+0QZ2b9iSjMBmk6hqfUR1vTMcikoDW/TgD3xvk1xjvSydzlhIMZYa6XF2bfZeZeJQwKrGt3LZa+y9JCUmfQD2FqntAwSOiaBRQ1AkWNDnpHbs2KYQLRAiAlAMcW4N/qGk2UEGxbwR8bsNeRV2jTgXfAojKkJJIBqY1HwKUyVvRyHhYOf21RlYSPxhYW4ixNXzIZu1oGCHniWmttv3fs4btGU/g+1aWJFiFjRf7vRGUy2Fwc1utTjAVWP0JQ/Q6c/KMoepdIoTZ394co4xzOK9AJqWijyi1Zy5l+/TttP5eQ//BQ/f6+wsCAwEAAQ=="

opendkim_internalhosts:
  - "127.0.0.1"
  - "::1"
  - "85.209.118.164"
  - "2a09:94c4:55d1:7682::164"

mailman_fake_domain: "mailman.bornhack.org"
mailman_list_owner: "thomas@gibfest.dk"
mailman_primary_domain: "bornhack.org"

lmtp_server_ip: "imap3.servers.bornhack.org"
lmtp_server_port: "24"
sasl_server_ip: "imap3.servers.bornhack.org"
sasl_server_port: "12"

postgres_dbname: "smtp2_servers_bornhack_org_db"
postgres_user: "smtp2_servers_bornhack_org"

lists:
  badge: "tykling@bornhack.org"
  bar-team: "sarah@radicalpet.net"
  ccc2019: "tykling@bornhack.org"
  cert-team: "fonsmark@bornhack.org"
  conduct: "tykling@bornhack.org"
  content: "ahf@bornhack.org"
  economy-team: "tykling@bornhack.org"
  food-team: "tykling@bornhack.org"
  gis-team: "ahf@bornhack.org"
  info: "tykling@bornhack.org"
  info-team: "graffen@gmail.com"
  logistics-team: "tykling@bornhack.org"
  metrics: "tykling@bornhack.org"
  noc-team: "hlk@kramse.org"
  noc: "hlk@kramse.org"
  orga: "tykling@bornhack.org"
  power-team: "tykling@bornhack.org"
  pr-team: "ahf@bornhack.org"
  program-team: "ahf@bornhack.org"
  sanitation-team: "tykling@bornhack.org"
  speakers: "ahf@bornhack.org"
  sponsors: "ahf@bornhack.org"
  shuttle: "tykling@bornhack.org"
  youtube: "vidir@bornhack.org"
  villages-team: "sarah@radicalpet.net"
  gameteam: "tykling@bornhack.org"

vhosts:
  mail_bornhack_org:
    vhost_v6ip: "2a09:94c4:55d1:7682::164"
    hostnames:
      - "smtp2.servers.bornhack.org"
      - "mail.bornhack.org"
    default_vhost: True
    locationslash: |
        location = / {
                rewrite ^ /mailman/listinfo permanent;
        }
        location / {
                rewrite ^ /mailman$uri?$args;
        }
        location = /mailman/ {
                rewrite ^ /mailman/listinfo permanent;
        }
        location /mailman/ {
                proxy_pass http://127.0.0.1:8080/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
        }
        location /cgi-bin {
                rewrite ^/cgi-bin(.*)$ $1 permanent;
        }
        location /images/mailman {
                alias /usr/local/mailman/icons;
        }
        location /icons {
                alias /usr/local/mailman/icons;
        }
        location /pipermail {
                alias /usr/local/mailman/archives/public;
                autoindex on;
        }
        location /.well-known/acme-challenge/ {
                return 301 {{ certgrinder_redirect_url }}$request_uri;
        }

certgrinder_hostname_sets:
  - "smtp2.servers.bornhack.org,mx.bornhack.org,asmtp.bornhack.org,mail.bornhack.org"
