---
django_checkout_path: "/usr/local/www/wwwstaging.bornhack.org"
django_root: "{{ django_checkout_path }}/src"
django_mainapp: bornhack
django_allowed_hostnames: "['wwwstaging.bornhack.org']"
django_debug: 'False'
django_nginx_static_root: "{{ django_root }}/static/"
django_github_repo_url: https://github.com/bornhack/bornhack-website
django_github_branch: "teamcomms"
django_pip_requirements_path: "{{ django_root }}/requirements.txt"
django_postgres_user: bornhackstagingdk
django_postgres_host: 10.0.0.3
django_postgres_dbname: bornhackstagingdkdb
django_email_user: noreply@bornhack.org
django_email_port: 587
django_email_host: mail.bornhack.org
django_email_from: info@bornhack.dk
django_media_root: /storage/django_media_root
django_media_root_subdirs:
  - invoices
  - creditnotes
  - public

django_extra_os_dependencies:
  - graphics/jpeg-turbo
  - converters/wkhtmltopdf
  - x11-fonts/webfonts

django_archive_email: stagingemailarchive@bornhack.org
django_admins: |
  (
      ('bornhack sysadm', 'sysadm@bornhack.org'),
  )
django_timezone: 'Europe/Copenhagen'

supervisord_extra_programs:
  - name: "invoiceworker"
    comment: "run invoiceworker"
    command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py run_managepy_worker --sleep 30 shop.invoiceworker"
    user: "www"
    priority: "4"

  - name: "outgoingemailworker"
    comment: "run outgoingemailworker"
    command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py run_managepy_worker --sleep 30 utils.outgoingemailworker"
    user: "www"
    priority: "4"

  - name: "ircworker"
    comment: "run ircworker"
    command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py run_managepy_worker --sleep 10 ircbot.ircworker"
    user: "www"
    priority: "4"


pdf_archive_path: '/storage/pdf_archive/'
pdf_letterhead_filename: "bornhack-2018_test_letterhead.pdf"
iban: DK3553710000244504
swiftbic: ALBADKKK
regno: 5371
accountno: 244504
bank_name: "Arbejdernes Landsbank"

nginx_locationslash: |
  location /static/ {
        alias {{ django_nginx_static_root }};
  }
  location /public/ {
        internal;
        root {{ django_media_root }};
  }
  location @django {
      proxy_pass http://127.0.0.1:8000;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
  }
  location / {
        root {{ django_nginx_static_root }}img/favicon;
        try_files $uri @django;
  }

django_ircbot_nickname: "BornHackStaging"
django_ircbot_server: "ircd.tyknet.dk"
django_ircbot_public_channel: "#tirsdagsfilm"
django_ircbot_nickserv_mask: "NickServ@services.baconsvin.org"
django_ircbot_chanserv_mask: "ChanServ@services.baconsvin.org"
django_ircbot_nickserv_email: "stagingbot@bornhack.org"

django_sendfile_url: "/public"
django_sendfile_backend: "sendfile.backends.nginx"

